/**
 * Locks `@hungpvq/vue-map-core` root **runtime** export surface.
 * Type-only exports are documented on `libs/map-core/core/docs/core/stable-api.md`
 * and are erased at runtime — intentionally omitted here.
 *
 * Adding a runtime symbol: update Stable or Experimental list here + stable-api.md.
 */
import { describe, expect, it } from 'vitest';
import * as api from './index';

/** Stable root runtime exports (SemVer contract for 1.x). */
export const VUE_MAP_CORE_STABLE_RUNTIME_EXPORTS = [
  'BaseMapControl',
  'BaseMapTagControl',
  'CompareBaseMapControl',
  'CompareSettingControl',
  'CrsControl',
  'EventManagementControl',
  'FullScreenControl',
  'GeoLocateControl',
  'GlobeControl',
  'GotoControl',
  'HomeControl',
  'InfoControl',
  'LegendControl',
  'Map',
  'MapContextMenuControl',
  'MeasurementControl',
  'ModuleContainer',
  'MouseCoordinatesControl',
  'PrintAdvancedControl',
  'PrintControl',
  'RegistryControl',
  'RegistryItem',
  'SettingControl',
  'ThemeControl',
  'ToolbarControl',
  'UniversalRegistry',
  'WorkerControl',
  'ZoomControl',
  'useMap',
  'useRegisterMapControl',
  'useShow',
  'useUniversalRegistry',
] as const;

/** @experimental — may change in a minor. */
export const VUE_MAP_CORE_EXPERIMENTAL_RUNTIME_EXPORTS = [
  'BaseButton',
  'BaseMapAdapter',
  'BaseMapCard',
  'Collapse',
  'CompareBaseMapCard',
  'CompareSettingCard',
  'CrsDisplaySettings',
  'DefaultBaseMapAdapter',
  'FormView',
  'InputCheckbox',
  'InputChoose',
  'InputColorPicker',
  'InputCrs',
  'InputFile',
  'InputSelect',
  'InputSlider',
  'InputText',
  'InputTextArea',
  'KEY',
  'MITT_KEY',
  'MapButton',
  'MapCard',
  'MapCommonButton',
  'MapCompare',
  'MapControlButton',
  'MapControlGroupButton',
  'MapErrorHandler',
  'MapIcon',
  'MapImage',
  'MapLegend',
  'MapMarkerView',
  'MapView',
  'MeasurementHandle',
  'MeasurementService',
  'MeasurementSettingPopup',
  'View',
  'addCursorCrosshair',
  'createSubscribable',
  'createToolbarControl',
  'createToolbarModule',
  'defaultMapProps',
  'errorHandler',
  'getLegendName',
  'getMapCompare',
  'getMapCompareSetting',
  'isDisabledLegendLayer',
  'isSupportGenLayerLegend',
  'langStore',
  'makeShowProps',
  'removeCursorCrosshair',
  'useBaseMap',
  'useBaseMapAdapter',
  'useComponentName',
  'useCoordinate',
  'useEventListener',
  'useEventMap',
  'useEventMapItems',
  'useInitToolbarControl',
  'useLang',
  'useLayerLegend',
  'useMapBaseMapStore',
  'useMapCrsCurrent',
  'useMapCrsDisplayEpsgs',
  'useMapCrsItems',
  'useMapCrsStore',
  'useMapEventStore',
  'useMapImage',
  'useMapImages',
  'useMapInstance',
  'useMapMittStore',
  'useMapPrint',
  'useMapPrintStore',
  'useMapState',
  'useMapToolbar',
  'useMapToolbarModule',
  'useMapToolbarStore',
  'useToolbarControl',
  'useWorkerMonitor',
  'withMapProps',
] as const;

describe('public API surface', () => {
  it('root runtime exports match Stable + Experimental allowlists', () => {
    const keys = Object.keys(api).sort();
    const expected = [...VUE_MAP_CORE_STABLE_RUNTIME_EXPORTS, ...VUE_MAP_CORE_EXPERIMENTAL_RUNTIME_EXPORTS].sort();
    expect(keys).toEqual(expected);
  });
});
