/**
 * Locks `@hungpvq/map-core` **runtime** export surface for the root entry and
 * every domain subpath entry (`/basemap`, `/crs`, `/event`, `/image`, `/legend`,
 * `/measurement`, `/menu`, `/print`, `/theme`, `/toolbar`).
 *
 * Type-only first-party exports use explicit `export type { … }` (see stable-api.md);
 * do not re-export third-party (`geojson` / `maplibre-gl`) types from any entry.
 * Runtime type-only symbols are erased and omitted from these locks.
 *
 * Every public barrel must use **named** exports only (no public `export *`).
 * Adding a runtime symbol: named export in the entry barrel + Stable or
 * Experimental list here + stable-api.md.
 */
import { describe, expect, it } from 'vitest';
import * as basemapApi from './basemap';
import * as devtoolsApi from './devtools';
import * as crsApi from './crs';
import * as eventApi from './event';
import * as imageApi from './image';
import * as api from './index';
import * as legendApi from './legend';
import * as measurementApi from './measurement';
import * as menuApi from './menu';
import * as printApi from './print';
import * as themeApi from './theme';
import * as toolbarApi from './toolbar';

/** Stable root runtime exports (SemVer contract for 1.x). */
export const MAP_CORE_STABLE_RUNTIME_EXPORTS = [
  'abortWorkerMonitorTask',
  'anyWorkerHasHistory',
  'applyWorkerMonitorMessage',
  'Base',
  'bboxFromGeojson',
  'bindMapKeyboardShortcuts',
  'bindMapLongPress',
  'buildMapControlHandle',
  'buildModuleBindPosition',
  'BUTTON_IN_MOBILE_VALUES',
  'closeTopOpenMapControl',
  'connectWorkerMonitor',
  'convertGeometry',
  'ACTION_FEEDBACK_MS',
  'COPY_FEEDBACK_MS',
  'copyImageDataUrl',
  'copyText',
  'countBusyWorkers',
  'createActionFeedback',
  'createCopyFeedback',
  'createDefaultLangStore',
  'createMapLocaleApi',
  'DEFAULT_MAP_BREAKPOINTS',
  'flattenLocaleMessages',
  'getLocaleProp',
  'getStoredMapLanguage',
  'interpolateLocale',
  'isMapLangFlatMessages',
  'mapLanguageCodeLabel',
  'nextMapLanguageInList',
  'registerLanguageControlPacks',
  'resolveInitialMapLanguage',
  'translateMapLang',
  'translateMapLangFromCatalog',
  'unflattenLocaleMessages',
  'bootstrapMapLanguage',
  'createMapMitt',
  'createWorkerMonitorAbortMessage',
  'createWorkerMonitorLogMessage',
  'createWorkerMonitorProgressMessage',
  'deepMergeLocale',
  'diffLocaleKeys',
  'setStoredMapLanguage',
  'MAP_BUILTIN_LANGUAGES',
  'MAP_LANGUAGE_STORAGE_KEY',
  'LANGUAGE_CONTROL_LOCALE',
  'MAP_CORE_LOCALE_EN',
  'MAP_CORE_LOCALE_VI',
  'degToDms',
  'degToDmsString',
  'dmsToDeg',
  'downloadDataUrl',
  'EMPTY_MAP_VIEW_INFO',
  'applyGotoSetting',
  'applyMapScaleLabel',
  'applyMapStyleSettings',
  'attachGlobeProjectionListener',
  'attachMapViewInfoListeners',
  'attachRotateListener',
  'bearingToCompassTransform',
  'captureHomeView',
  'debounce',
  'formatMapScaleLabel',
  'getProjectionType',
  'getRoundNum',
  'goHome',
  'gotoSettingFromCoordinateText',
  'inputToSprite',
  'isGlobeProjection',
  'readGotoSetting',
  'readMapStyleSettings',
  'resetBearing',
  'resolveOriginalEvent',
  'spriteToInput',
  'toggleGlobeProjection',
  'zoomIn',
  'zoomOut',
  'errorHandler',
  'exitDocumentFullscreen',
  'FallbackResolver',
  'filterMapControls',
  'filterWorkerSnapshots',
  'fitBounds',
  'focusMapLayerSearch',
  'formatCoordinate',
  'formatCoordPair',
  'formatDegree',
  'formatLngLatBounds',
  'formatNumber',
  'formatProjectionName',
  'formatWorkerDuration',
  'formatWorkerLogTime',
  'getChartRandomColor',
  'getFullscreenElement',
  'getMap',
  'getMapBreakpointThreshold',
  'getMapPointerProfile',
  'GLOBE_CONTROL_LOCALE',
  'GOTO_CONTROL_LOCALE',
  'hasMapInstance',
  'HOME_CONTROL_LOCALE',
  'INFO_CONTROL_LOCALE',
  'installGlobalErrorCapture',
  'isCallStackOverflow',
  'isCoordinatesNumber',
  'isDocumentFullscreen',
  'isMapButtonFluidVariant',
  'isMapButtonSize',
  'isMapButtonSizeName',
  'isMapButtonSquareVariant',
  'isMapButtonVariant',
  'isMapRootFullscreen',
  'isModuleCornerChromeVisible',
  'isUsableMapId',
  'isValidBbox',
  'isWorkerBusy',
  'isWorkerMonitorAbortMessage',
  'isWorkerMonitorLogMessage',
  'isWorkerMonitorProgressMessage',
  'latDMS',
  'listMapPlatformHosts',
  'lngDMS',
  'logHelper',
  'MAP_ACTION_LOCALE',
  'MAP_BUTTON_SIZE_PX',
  'MAP_BUTTON_SIZES',
  'MAP_BUTTON_VARIANTS',
  'MAP_CORE_EVENT',
  'MAP_LAYER_SEARCH_SELECTOR',
  'MAP_MODULE_CONTROL_ID_KEY',
  'MAP_PLATFORM_HOST',
  'MAP_PLATFORM_REGISTRY_METHOD',
  'MAP_STORE_KEY',
  'MapError',
  'MapErrorHandler',
  'MapEventError',
  'MapInitializationError',
  'MapInitializer',
  'MapStoreManager',
  'mapBreakpointGreaterOrEqual',
  'mapBreakpointSmallerOrEqual',
  'mapButtonSizeClass',
  'mapButtonVariantClass',
  'mapLayerSearchSelector',
  'mergeFilters',
  'moduleBtnContainerClassName',
  'moduleCornerHostId',
  'moduleCornerHostSelector',
  'moduleDraggableHostId',
  'moduleDraggableHostSelector',
  'MittTypeMapEventKey',
  'MittTypeMapLangEventKey',
  'parseCoordinateListText',
  'parseCoordinateText',
  'queryModuleHostElement',
  'readMapViewInfo',
  'registerMapAccessor',
  'registerMapReadySubscriber',
  'registerMapStoreCleanup',
  'registerMapStoreCleanupRegistrar',
  'REGISTRY_CONTROL_LOCALE',
  'REGISTRY_CONTROLS_STORE_KEY',
  'REGISTRY_GLOBAL_STORE_KEY',
  'REGISTRY_MAPS_STORE_KEY',
  'REGISTRY_NAMESPACES',
  'reprojectGeojson',
  'reprojectGeojsonToWgs84',
  'requestElementFullscreen',
  'resolveControlLayout',
  'resolveMapBreakpointFlags',
  'resolveMapBreakpoints',
  'resolveMapButtonSizeName',
  'resolveMapButtonSizePx',
  'resolveMapFullscreenTarget',
  'resolveSelectedWorkerId',
  'runMapControlAction',
  'runMonitoredTask',
  'runWorkerMonitor',
  'SETTING_CONTROL_LOCALE',
  'subscribeFullscreenChange',
  'subscribeMapReady',
  'toCoordinatesNumberList',
  'toPlainJson',
  'toggleElementFullscreen',
  'UniversalRegistry',
  'WORKER_CONTROL_LOCALE',
  'workerHasHistory',
  'workerLogsForDisplay',
  'WorkerMonitor',
  'workerProgressRatio',
] as const;

/** Experimental root exports (may change in a minor). */
export const MAP_CORE_EXPERIMENTAL_RUNTIME_EXPORTS = [
  'DEVTOOLS_CONTROL',
  'GeoLocateSession',
] as const;

/** Experimental `@hungpvq/map-core/devtools` runtime exports. */
export const MAP_CORE_DEVTOOLS_EXPERIMENTAL_RUNTIME_EXPORTS = [
  'BufferingLogAdapter',
  'clearDevtoolErrors',
  'clearDevtoolLogs',
  'createDevtoolLogAdapter',
  'DEVTOOLS_CONTROL',
  'DEVTOOLS_MOBILE_BREAKPOINT',
  'formatDevtoolsLogEntryForCopy',
  'getDevtoolState',
  'initDevtoolStoreCore',
  'installDevtoolErrorListener',
  'installDevtoolsCore',
  'installDevtoolsErrorsShortcut',
  'isDevtoolsMobileViewport',
  'isMapDevtoolsInstalled',
  'openMapDevtoolsErrors',
  'OPEN_DEVTOOLS_ERRORS_EVENT',
  'replaceDevtoolErrors',
  'replaceDevtoolLogs',
  'resolveMapDragContainerId',
  'setDevtoolActiveTab',
  'setDevtoolOpen',
  'subscribeDevtoolState',
  'toggleDevtoolOpen',
] as const;

/** Stable runtime exports per domain subpath entry. */
export const MAP_CORE_SUBPATH_RUNTIME_EXPORTS = {
  basemap: [
    'BASEMAP_CONTROL_LOCALE',
    'BASEMAP_PREFIX',
    'BaseMapAdapter',
    'BaseMapLayer',
    'BasemapError',
    'BasemapManager',
    'BasemapService',
    'createDefaultBaseMapAdapter',
    'createDefaultBaseMapAdapterClass',
    'DefaultBaseMapAdapter',
    'getLowestLayerId',
    'INIT_BASEMAPS',
    'MittTypeBaseMapEventKey',
    'subscribeBasemapMirror',
  ],
  crs: [
    'buildCrsSearchCatalog',
    'buildMapCrsCatalog',
    'createCoordinateFormatter',
    'createDefaultCrsStore',
    'createMapDisplayCoordinateFormatter',
    'CRS_CONTROL_LOCALE',
    'DEFAULT_CRS_ITEMS',
    'enrichCrsItemProjection',
    'formatCrsLabel',
    'getCrsInputSuggestions',
    'INITIAL_MAP_CRS_ITEMS',
    'lookupCrsItem',
    'MittTypeMapCrsEventKey',
    'normalizeDisplayEpsgs',
    'normalizeEpsgCode',
    'resolveCrsDisplayItems',
    'resolveCrsItemForStore',
    'resolveCrsProjection',
    'searchCrsCatalog',
  ],
  event: [
    'createDefaultEventStore',
    'createEventActionSync',
    'Event',
    'EVENT_CONTROL_LOCALE',
    'EventBboxRanger',
    'EventClick',
    'EventContextMenu',
    'EventManager',
    'EventMouseMove',
    'groupEventsByMapType',
    'isEventActive',
    'MittTypeMapEventEventKey',
    'normalizeEventFrom',
    'startBoxRangerMap',
  ],
  image: [
    'addImageForMap',
    'createDefaultImageStore',
    'createMapImageStoreApi',
    'listMapStyleImages',
    'loadImage',
    'patchMapStyleImageAccessors',
    'styleImageToDataURL',
    'subscribeMapStyleImages',
    'toImageDataFromRGBAImage',
  ],
  legend: [
    'buildLayerLegendElements',
    'cache',
    'Circle',
    'exprHandler',
    'Fill',
    'getLegendName',
    'isDisabledLegendLayer',
    'isSupportGenLayerLegend',
    'LAYER_LEGEND_FALLBACK_PATHS',
    'LEGEND_CONTROL_LOCALE',
    'LegendService',
    'Line',
    'MapLegend',
    'mapImageToDataURL',
    'Symbol',
  ],
  measurement: [
    'addCursorCrosshair',
    'buildMeasurementGeojsonDownload',
    'createMeasurementMapView',
    'createMeasurementMapViewEmptySource',
    'createMeasurementMapViewLayers',
    'createMeasurementSession',
    'draftCoordinatesToFeature',
    'edgeLabelRotation',
    'formatAreaText',
    'formatDistanceText',
    'FormView',
    'getMeasurementAreaUnit',
    'getMeasurementDistanceUnit',
    'getMeasurementLabelPrefs',
    'getMeasurementSettingUiFlags',
    'MapMarkerView',
    'MapView',
    'Measure',
    'MeasureArea',
    'MeasureAngle',
    'MeasureAzimuth',
    'MeasureDistance',
    'MEASUREMENT_CONTROL_LOCALE',
    'MEASUREMENT_DEFAULT_HIGHLIGHT_COLOR',
    'MEASUREMENT_MAP_VIEW_IMAGE',
    'MeasurementHandle',
    'MeasurementService',
    'MeasurePoint',
    'MeasureRadius',
    'removeCursorCrosshair',
    'resolveMeasurementModeToggle',
    'resolveMeasurementToolbarStatus',
    'setMeasurementAreaUnit',
    'setMeasurementDistanceUnit',
    'setMeasurementLabelPrefs',
    'View',
  ],
  menu: [
    'centerMapHere',
    'clearAddGeojsonHereItems',
    'copyMapPointAsGeojson',
    'copyMapPointCoords',
    'copyMapPointWkt',
    'createAddGeojsonHereDef',
    'createBufferHereDef',
    'createDefaultMapContextMenuItems',
    'createMapMenuBuilder',
    'createMapMenuItemProps',
    'createMenuItemCenterMapHere',
    'createMenuItemCopyAsGeojson',
    'createMenuItemCopyCoords',
    'createMenuItemCopyWkt',
    'createMenuItemGoogleEarth',
    'createMenuItemGoogleMaps',
    'createMenuItemIdentifyHere',
    'createMenuItemQuickAnalysis',
    'createMenuItemsAddGeojsonHere',
    'createMenuItemZoomInHere',
    'filterVisibleMapMenuItems',
    'formatMapContextCoords',
    'getDefaultAddGeojsonHereItems',
    'handleMapMenuAction',
    'identifyFeaturesHere',
    'MAP_CONTEXT_MENU_ID',
    'openGoogleEarth',
    'openGoogleMaps',
    'pointFeatureGeojson',
    'pointWkt',
    'resolveMapMenuCondition',
    'setAddGeojsonHereItems',
    'zoomInMapHere',
  ],
  print: [
    'createDefaultPrintStore',
    'createPrintAdvancedSession',
    'createPrintStoreApi',
    'CrosshairManager',
    'DEFAULT_PRINT_ADVANCED_SETTING',
    'exportFile',
    'clipCanvasRegion',
    'exportMapbox',
    'exportMapboxWithOptions',
    'Format',
    'getMapBoxCanvas',
    'PRINT_CONTROL_LOCALE',
    'PRINT_PAPER_PRESETS',
    'PrintableAreaManager',
    'printMapToFile',
    'PrintService',
    'waitMapIdleAndTiles',
  ],
  theme: [
    'applyMapTheme',
    'applyMapThemeClass',
    'applyMapThemeClassToElement',
    'applyMapThemeContrastClass',
    'applyMapThemeForMap',
    'bootstrapMapTheme',
    'cycleMapThemeMode',
    'getMapThemeLocaleKey',
    'getMapThemeStorageKey',
    'getPrefersContrastMore',
    'getPrefersDark',
    'getStoredMapThemeMode',
    'isMapThemeId',
    'isMapThemeMode',
    'MAP_THEME_CLASS',
    'MAP_THEME_COLOR_SCHEME',
    'MAP_THEME_CONTRAST_CLASS',
    'MAP_THEME_IDS',
    'MAP_THEME_MODES',
    'MAP_THEME_STORAGE_KEY',
    'normalizeMapThemeModes',
    'resolveMapTheme',
    'resolveMapThemeElement',
    'setStoredMapThemeMode',
    'subscribePrefersContrastMore',
    'THEME_CONTROL_LOCALE',
    'toggleMapThemeLightDark',
  ],
  toolbar: [
    'BUTTON_GROUP_OVERFLOW_FRACTION',
    'compassIcon',
    'createDefaultToolbarStore',
    'createLiveToolbarStrategy',
    'createSubscribable',
    'createToolbarControl',
    'createToolbarModule',
    'createToolbarModuleApi',
    'createToolbarStoreApi',
    'createToolbarStrategy',
    'cornerVerticalMenuBudgetsPx',
    'elementOuterSize',
    'groupToolbarButtons',
    'maxVisibleButtonsInStackHeight',
    'maxVisibleToolbarButtons',
    'measureCornerMenuUsedPx',
    'measureCornerStandaloneReserved',
    'mdiButtonState',
    'mdiIcon',
    'textButtonState',
    'planToolbarLayout',
    'splitToolbarOverflow',
    'splitToolbarOverflowKeepGroups',
    'TOOLBAR_CONTROL_LOCALE',
    'TOOLBAR_EDGE_INSET_PX',
    'TOOLBAR_STACK_GAP_PX',
    'toolbarAvailableWidth',
    'toolbarGroupHeightCost',
    'toolbarOverflowPanelClassName',
    'TOOLBAR_STRATEGIES',
  ],
} as const;

const SUBPATH_MODULES: Record<
  keyof typeof MAP_CORE_SUBPATH_RUNTIME_EXPORTS,
  Record<string, unknown>
> = {
  basemap: basemapApi,
  crs: crsApi,
  event: eventApi,
  image: imageApi,
  legend: legendApi,
  measurement: measurementApi,
  menu: menuApi,
  print: printApi,
  theme: themeApi,
  toolbar: toolbarApi,
};

describe('public API surface', () => {
  it('root runtime exports match Stable + Experimental allowlists', () => {
    const keys = Object.keys(api).sort();
    const expected = [
      ...MAP_CORE_STABLE_RUNTIME_EXPORTS,
      ...MAP_CORE_EXPERIMENTAL_RUNTIME_EXPORTS,
    ].sort();
    expect(keys).toEqual(expected);
  });

  it.each(
    Object.keys(MAP_CORE_SUBPATH_RUNTIME_EXPORTS) as Array<
      keyof typeof MAP_CORE_SUBPATH_RUNTIME_EXPORTS
    >,
  )('subpath entry `%s` runtime exports match the allowlist', (name) => {
    const keys = Object.keys(SUBPATH_MODULES[name]).sort();
    const expected = [...MAP_CORE_SUBPATH_RUNTIME_EXPORTS[name]].sort();
    expect(keys).toEqual(expected);
  });

  it('root entry does not re-export domain symbols', () => {
    const rootKeys = new Set(Object.keys(api));
    const overlap: string[] = [];
    for (const names of Object.values(MAP_CORE_SUBPATH_RUNTIME_EXPORTS)) {
      for (const name of names) if (rootKeys.has(name)) overlap.push(name);
    }
    expect(overlap).toEqual([]);
  });

  it('devtools subpath runtime exports match the Experimental allowlist', () => {
    const keys = Object.keys(devtoolsApi).sort();
    const expected = [...MAP_CORE_DEVTOOLS_EXPERIMENTAL_RUNTIME_EXPORTS].sort();
    expect(keys).toEqual(expected);
  });
});
