/**
 * Dual Vue ↔ React parity catalog (test / docs source of truth).
 * Not a package public entry — imported by parity specs only.
 */

/** Control / toolbar ids that must appear in both Vue and React adapter sources. */
export const MAP_DUAL_CONTROL_IDS = [
  'mapLayerControl',
  'mapDatasetControl',
  'mapGotoControl',
  'mapSettingControl',
  'mapInfoControl',
  'mapWorkerControl',
  'mapIdentifyControl',
  'mapCrsControl',
  'mapLegendControl',
  'mapBaseMapControl',
  'mapEventManagementControl',
  'mapHomeControl',
  'mapFullscreenControl',
  'mapThemeControl',
  'mapGeoLocateControl',
  'mapGlobeControl',
  'mapPrintControl',
  'mapNavigationControl',
  'mapMeasurementControl',
  'mapPrintAdvancedControl',
  'mapInspectControl',
  'mapDrawDraftList',
  'mapRegistryControl',
  'mapAttributeTable',
  'mapMeasurementSetting',
  'mapCreateControl',
] as const;

/**
 * Stable root exports that both `@hungpvq/vue-map-core` and `@hungpvq/react-map-core`
 * must publish (framework-idiom symbols excluded).
 */
export const MAP_CORE_ADAPTER_SHARED_STABLE = [
  'ActionControl',
  'BaseMapCard',
  'BaseMapControl',
  'BaseMapTagControl',
  'CrsControl',
  'CrsDisplaySettings',
  'DefaultBaseMapAdapter',
  'EventManagementControl',
  'FullScreenControl',
  'GeoLocateControl',
  'GlobeControl',
  'GotoControl',
  'HomeControl',
  'InfoControl',
  'LegendControl',
  'Map',
  'MapCommonButton',
  'MapContextMenuControl',
  'MapControlButton',
  'MapControlGroupButton',
  'MeasurementControl',
  'MeasurementSettingPopup',
  'ModuleContainer',
  'MouseCoordinatesControl',
  'PrintAdvancedControl',
  'PrintControl',
  'RegistryControl',
  'RegistryItem',
  'SettingControl',
  'ThemeControl',
  'ToolbarControl',
  'UniversalRegistry',
  'WorkerControl',
  'ZoomControl',
  'addStore',
  'createMapScopedStore',
  'defaultMapProps',
  'destroyMapScopedStore',
  'getStore',
  'langStore',
  'useBaseMap',
  'useBaseMapAdapter',
  'useComponentName',
  'useCoordinate',
  'useEventListener',
  'useEventMap',
  'useEventMapItems',
  'useInitToolbarControl',
  'useLang',
  'useLayerLegend',
  'useMap',
  'useMapBaseMapStore',
  'useMapContainer',
  'useMapCrsCurrent',
  'useMapCrsDisplayEpsgs',
  'useMapCrsItems',
  'useMapCrsStore',
  'useMapEventStore',
  'useMapGlobalStore',
  'useMapImage',
  'useMapImages',
  'useMapInstance',
  'useMapMittStore',
  'useMapPrint',
  'useMapPrintStore',
  'useMapState',
  'useMapStore',
  'useMapToolbar',
  'useMapToolbarModule',
  'useMapToolbarStore',
  'useRegisterMapControl',
  'useShow',
  'useToolbarControl',
  'useUniversalRegistry',
  'useWorkerMonitor',
] as const;

/** Shared Experimental field helpers on `./fields` (aliases included). */
export const MAP_CORE_ADAPTER_SHARED_EXPERIMENTAL = [
  'BaseCollapse',
  'Collapse',
  'InputCheckbox',
  'InputChoose',
  'InputColorPicker',
  'InputCrs',
  'InputFile',
  'InputSelect',
  'InputSlider',
  'InputText',
  'InputTextArea',
  'InputTextarea',
  'MapButton',
  'MapCard',
  'MapErrorToast',
  'MapIcon',
  'MapImage',
] as const;

export const MAP_DATASET_ADAPTER_SHARED_STABLE = [
  'AddToGroup',
  'AttributeTable',
  'ComponentManagementControl',
  'CreateControl',
  'createDatasetRegistryPlugin',
  'createLegend',
  'createMultiLegend',
  'DatasetControl',
  'DatasetDetail',
  'DatasetMenuButton',
  'ExportGeo',
  'IdentifyControl',
  'IdentifyLayerAction',
  'IdentifyResultControl',
  'IdentifyShowFirstControl',
  'installMapApp',
  'LayerControl',
  'LayerDetail',
  'LayerHighlight',
  'LayerInfoControl',
  'LayerItemIcon',
  'LayerMenuDefaultHandle',
  'ListGroupItem',
  'ListItem',
  'RecursiveList',
  'SetOpacity',
  'StyleControl',
  'ToggleShow',
  'ToggleShowButton',
  'useMapDataset',
  'useMapDatasetComponent',
  'useMapDatasetComponentStore',
  'useMapDatasetHighlight',
  'useMapDatasetHighlightStore',
  'useMapDatasetStore',
  'useMenuConditionContext',
  'useToggleShowAction',
] as const;

export const MAP_DRAW_ADAPTER_SHARED_STABLE = [
  'DRAW_CONTROL_LOCALE',
  'DrawControl',
  'INSPECT_CONTROL_LOCALE',
  'InspectControl',
  'isDraftOption',
  'useConfigDrawControl',
  'useMapDraw',
  'useMapDrawStore',
] as const;

/** Canonical Experimental names — prefer these in new code. */
export const MAP_CORE_EXPERIMENTAL_CANONICAL = {
  collapse: 'BaseCollapse',
  textArea: 'InputTextArea',
} as const;

/**
 * MapControlButton / MapButton public prop contract (SoT in `@hungpvq/map-core` `ui/map-button`).
 * Both adapters must import helpers from core — do not fork variant/size literals.
 */
export const MAP_CONTROL_BUTTON_VARIANTS = [
  'icon',
  'plain',
  'text',
  'tonal',
  'outlined',
  'filled',
] as const;

export const MAP_CONTROL_BUTTON_SIZES = ['small', 'medium', 'large'] as const;
