/**
 * Locks `@hungpvq/react-map-core` root **runtime** export surface.
 * Type-only first-party exports use explicit `export type { … }` (see stable-api.md);
 * do not re-export third-party (`geojson` / `maplibre-gl`) types from the root.
 * Runtime type-only symbols are erased and omitted from this lock.
 *
 * Root `index.ts` must use **named** exports only (no public `export *`).
 * Adding a runtime symbol: named export in `index.ts` + Stable or Experimental list here + stable-api.md.
 */
import { describe, expect, it } from 'vitest';
import * as api from './index';

/** Stable root runtime exports (SemVer contract for 1.x). */
export const REACT_MAP_CORE_STABLE_RUNTIME_EXPORTS = [
  'BaseMapControl',
  'BaseMapTagControl',
  'CompareBaseMapControl',
  'CompareSettingControl',
  'CrsControl',
  'EventManagementControl',
  'FullScreenControl',
  'GeoLocateControl',
  'GlobeControl',
  'GotoControl',
  'HomeControl',
  'InfoControl',
  'LegendControl',
  'Map',
  'MapContextMenuControl',
  'MeasurementControl',
  'ModuleContainer',
  'MouseCoordinatesControl',
  'PrintAdvancedControl',
  'PrintControl',
  'RegistryControl',
  'RegistryItem',
  'SettingControl',
  'ThemeControl',
  'ToolbarControl',
  'UniversalRegistry',
  'WorkerControl',
  'ZoomControl',
  'useMap',
  'useRegisterMapControl',
  'useShow',
  'useUniversalRegistry',
] as const;

/** @experimental — may change in a minor. */
export const REACT_MAP_CORE_EXPERIMENTAL_RUNTIME_EXPORTS = [
  'ActionControl',
  'BaseButton',
  'BaseCollapse',
  'BaseMapAdapter',
  'BaseMapCard',
  'CompareBaseMapCard',
  'CompareSettingCard',
  'CrsDisplaySettings',
  'DefaultBaseMapAdapter',
  'DragDropFile',
  'InputCheckbox',
  'InputChoose',
  'InputColorPicker',
  'InputCrs',
  'InputFile',
  'InputSelect',
  'InputSlider',
  'InputText',
  'InputTextarea',
  'MapButton',
  'MapCard',
  'MapCommonButton',
  'MapCompare',
  'MapContext',
  'MapContextProvider',
  'MapControlButton',
  'MapControlButtonGroupContext',
  'MapControlGroupButton',
  'MapGlobalStoreProvider',
  'MapIcon',
  'MapImage',
  'MeasurementSettingPopup',
  'ReactMapStoreAdapter',
  'addStore',
  'createMapScopedStore',
  'createSubscribable',
  'createToolbarControl',
  'createToolbarModule',
  'defaultMapProps',
  'destroyMapScopedStore',
  'errorHandler',
  'getIsMulti',
  'getMap',
  'getMapCompare',
  'getMapCompareSetting',
  'getMapGlobalStore',
  'getMapMittStore',
  'getMapStore',
  'getMaps',
  'getStore',
  'handleError',
  'langStore',
  'logger',
  'updateMapCompareSetting',
  'useBaseMap',
  'useBaseMapAdapter',
  'useBreakpoints',
  'useComponentName',
  'useCoordinate',
  'useEventListener',
  'useEventMap',
  'useEventMapItems',
  'useInitToolbarControl',
  'useLang',
  'useLayerLegend',
  'useMapBaseMapStore',
  'useMapCompareSetting',
  'useMapContainer',
  'useMapContext',
  'useMapCrsCurrent',
  'useMapCrsDisplayEpsgs',
  'useMapCrsItems',
  'useMapCrsStore',
  'useMapEventStore',
  'useMapGlobalStore',
  'useMapImage',
  'useMapImages',
  'useMapInstance',
  'useMapMittStore',
  'useMapPrint',
  'useMapPrintStore',
  'useMapState',
  'useMapStore',
  'useMapToolbar',
  'useMapToolbarModule',
  'useMapToolbarStore',
  'useToolbarControl',
  'useWorkerMonitor',
] as const;

describe('public API surface', () => {
  it('root runtime exports match Stable + Experimental allowlists', () => {
    const keys = Object.keys(api).sort();
    const expected = [...REACT_MAP_CORE_STABLE_RUNTIME_EXPORTS, ...REACT_MAP_CORE_EXPERIMENTAL_RUNTIME_EXPORTS].sort();
    expect(keys).toEqual(expected);
  });
});
